# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fec555302669ce64fc2b011c1aa3f539e647f2523557f9f2cb330a10aff9388ea06fa66756c0e413b6db4b18015e3d8c4256097924caf1f3c7c4945c632018d4

test:
  secret_key_base: 54cabb08705bb694476559de7cf115cba45b50eeefa7b957973cd3d5f0870d54462c3f9adc7b4134c9bbd6de996df76bd1e1576636d88d6d05f2963211fffb59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
